language: 'java'

jdk:
  - oraclejdk8

notifications:
  on_success: never
  on_failure: always

deploy:
  provider: releases
  api_key: 69ea3670f5d71d899a0c09d1b9ba215b6996b1e6
  file: build/libs/*
  skip_cleanup: true
  on:
    tags: true
    repository: grizeldi/z21-drive
