language: 'java'

jdk:
  - oraclejdk8

notifications:
  on_success: never
  on_failure: always

deploy:
  provider: releases
  api_key: d4d9eafb91a42848358b19fe0cf71b96749b0957
  file: build/libs/*
  skip_cleanup: true
  on:
    tags: true
    repository: grizeldi/z21-drive