package z21Drive.record;

public enum Z21RecordType {
    //Response types
    LAN_GET_SERIAL_NUMBER_RESPONSE,
    LAN_X_GET_FIRMWARE_VERSION,
    LAN_GET_LOCOMODE_RESPONSE,
    LAN_X_STATUS_CHANGED,
    LAN_X_CV_RESULT,
    LAN_X_CV_NACK,
    LAN_RAILCOM_DATACHANGED,
    LAN_LOCONET_DETECTOR,

    //Broadcast type
    LAN_X_LOCO_INFO,
    LAN_X_UNKNOWN_COMMAND,
    LAN_X_TRACK_POWER_OFF,
    LAN_X_TRACK_POWER_ON,
    LAN_X_PROGRAMMING_MODE,
    LAN_X_SHORT_CIRCUIT,
    LAN_SYSTEMSTATE_DATACHANGED,
}
